(() => {
'use strict';
const TYPE={live:{label:'TV ao vivo',action:'get_live_categories'},vod:{label:'Filmes',action:'get_vod_categories'},series:{label:'Séries',action:'get_series_categories'}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const el={loginPanel:$('#loginPanel'),loginToggle:$('#loginPanelToggle'),loginSummary:$('#loginSummary'),login:$('#loginInput'),appName:$('#appNameInput'),liveExt:$('#liveExtensionInput'),server:$('#serverInput'),username:$('#usernameInput'),password:$('#passwordInput'),corsProxy:$('#corsProxyInput'),load:$('#loadButton'),status:$('#statusBox'),workspace:$('#workspace'),accountSummary:$('#accountSummary'),editLogin:$('#editLoginButton'),typeTabs:$('#typeTabs'),stylePanel:$('#stylePanel'),styleToggle:$('#styleToggle'),styleCurrent:$('#styleCurrent'),categoryTitle:$('#categoryTitle'),search:$('#categorySearch'),list:$('#categoryList'),viewport:$('#categoryViewport'),summary:$('#selectionSummary'),all:$('#selectAllButton'),clear:$('#clearTypeButton'),generate:$('#generateButton'),selectedCount:$('#selectedCount'),selectedTypes:$('#selectedTypes')};
const state={authenticated:false,loading:false,categories:[],selected:new Set(),activeType:'live'};
const SRH_MODULE_BASE='https://raw.githubusercontent.com/HyakkimaruPY/fei-config/main/html-generator/v6.6';
const TEMPLATE_REV='aura-generator-r11';
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function cleanCategoryName(value){let x=String(value||'');try{x=x.replace(/\p{Extended_Pictographic}/gu,'')}catch{}return x.replace(/[\uFE0F\u200D]/g,'').replace(/[\u{1F1E6}-\u{1F1FF}]/gu,'').replace(/^[\s|•·:;,_—–-]+|[\s|•·:;,_—–-]+$/g,'').replace(/\s{2,}/g,' ').trim()||'Categoria'}
function normalizeServer(s){return String(s||'').trim().replace(/\/+$/,'')}
function parseLogin(raw){let text=String(raw||'').trim();if(!text)throw new Error('Informe o M3U/login.');if(!/^https?:\/\//i.test(text))text='http://'+text;let u;try{u=new URL(text)}catch{throw new Error('URL inválida.')}let username=u.searchParams.get('username')||u.searchParams.get('user'),password=u.searchParams.get('password')||u.searchParams.get('pass');const path=u.pathname.split('/').filter(Boolean);if((!username||!password)&&path.length>=2&&!/\.php$/i.test(path[path.length-1])){username=username||decodeURIComponent(path[0]);password=password||decodeURIComponent(path[1])}if(!username||!password)throw new Error('Não encontrei username e password.');return{server:normalizeServer(u.origin),username,password,liveExtension:(u.searchParams.get('output')||'m3u8').toLowerCase()==='ts'?'ts':'m3u8'}}
function chosenMode(){return document.querySelector('input[name="appMode"]:checked')?.value||'standard'}
function chosenTheme(){return document.querySelector('input[name="theme"]:checked')?.value||'graphene'}
function apiUrl(action=''){const u=new URL(normalizeServer(el.server.value)+'/player_api.php');u.searchParams.set('username',el.username.value.trim());u.searchParams.set('password',el.password.value.trim());if(action)u.searchParams.set('action',action);return u.toString()}
function schemeTwin(url,scheme){try{const u=new URL(String(url||''));u.protocol=scheme+':';return u.href}catch{return''}}
function pushUnique(out,v){v=String(v||'').trim();if(v&&!out.includes(v))out.push(v)}
function proxyUrl(url){const base=String(el.corsProxy.value||'').trim(),raw=String(url||'').trim();if(!base)return raw;const enc=encodeURIComponent(raw);if(base.includes('{rawUrl}'))return base.split('{rawUrl}').join(raw);if(base.includes('{raw}'))return base.split('{raw}').join(raw);if(base.includes('{url}'))return base.split('{url}').join(enc);if(/[?&](?:url|target|uri|quest|q)=$/i.test(base)||base.endsWith('='))return base+enc;if(base.endsWith('?'))return base+enc;if(/\/fetch\/$/i.test(base))return base+raw;try{const u=new URL(base),known=['url','target','uri','quest','q'],key=known.find(k=>u.searchParams.has(k));u.searchParams.set(key||'url',raw);return u.toString()}catch{return base+(base.includes('?')?'&url=':'?url=')+enc}}
async function fetchJson(url){const c=typeof AbortController==='function'?new AbortController():null,t=c?setTimeout(()=>c.abort(),13000):0;try{const r=await fetch(url,{cache:'no-store',redirect:'follow',credentials:'omit',signal:c?.signal,headers:{Accept:'application/json,text/plain,*/*'}});if(!r.ok)throw new Error('HTTP '+r.status);const text=await r.text();try{return JSON.parse(text)}catch{throw new Error('resposta não é JSON')}}finally{if(t)clearTimeout(t)}}
async function request(action=''){const target=apiUrl(action),urls=[];if(location.protocol==='https:'&&/^http:\/\//i.test(target))pushUnique(urls,schemeTwin(target,'https'));pushUnique(urls,target);if(el.corsProxy.value.trim()){const p=proxyUrl(target);if(location.protocol==='https:'&&/^http:\/\//i.test(p))pushUnique(urls,schemeTwin(p,'https'));pushUnique(urls,p)}let last;for(const u of urls){try{return await fetchJson(u)}catch(e){last=e}}throw new Error((last?.message||'Falha no fetch.')+(el.corsProxy.value.trim()?' · proxy configurado também falhou.':' · sem Proxy CORS configurado.'))}
function normalizeCategories(data,type){return(Array.isArray(data)?data:[]).map((c,i)=>({type,id:String(c.category_id??c.id??i),name:String(c.category_name??c.name??('Categoria '+(i+1)))}))}
function setLoginOpen(open){el.loginPanel.classList.toggle('is-open',!!open)}
function setStatus(msg,kind=''){el.status.textContent=msg;el.status.className='status-strip'+(kind?' '+kind:'')}
function resetWorkspace(message='Aguardando análise.'){state.authenticated=false;state.categories=[];state.selected.clear();el.workspace.classList.add('is-hidden');el.list.innerHTML='';el.generate.disabled=true;updateSelection();setStatus(message)}
function availableTypes(){return chosenMode()==='shorts'?['vod']:['live','vod','series']}
function chooseInitialType(){state.activeType=chosenMode()==='shorts'?'vod':'live'}
function renderTypeTabs(){const types=availableTypes();$$('[data-type]').forEach(btn=>{const t=btn.dataset.type,visible=types.includes(t);btn.classList.toggle('is-hidden',!visible);btn.disabled=!visible;btn.classList.toggle('is-active',t===state.activeType&&visible)});updateTabCounts()}
function updateTabCounts(){for(const t of Object.keys(TYPE)){const count=state.categories.filter(c=>c.type===t&&state.selected.has(c.type+'::'+c.id)).length;const badge=document.querySelector(`[data-count="${t}"]`);if(badge)badge.textContent=count}}
function currentCategories(){const q=el.search.value.trim().toLocaleLowerCase('pt-BR');return state.categories.filter(c=>c.type===state.activeType&&(!q||c.name.toLocaleLowerCase('pt-BR').includes(q)||cleanCategoryName(c.name).toLocaleLowerCase('pt-BR').includes(q)))}
function renderCategories(){const allForType=state.categories.filter(c=>c.type===state.activeType),list=currentCategories();el.categoryTitle.textContent=TYPE[state.activeType].label+' · '+allForType.length;el.list.innerHTML=list.length?list.map(c=>{const key=c.type+'::'+c.id;return `<label class="category-option"><input type="checkbox" data-key="${escapeHtml(key)}" ${state.selected.has(key)?'checked':''}><span>${escapeHtml(cleanCategoryName(c.name))}</span></label>`}).join(''):`<div class="empty">Nenhuma categoria encontrada nesta seção.</div>`;el.list.querySelectorAll('[data-key]').forEach(ch=>ch.onchange=()=>{ch.checked?state.selected.add(ch.dataset.key):state.selected.delete(ch.dataset.key);updateSelection()});el.viewport.scrollTop=0}
function selectedCategories(){return state.categories.filter(c=>state.selected.has(c.type+'::'+c.id))}
function updateSelection(){const cats=selectedCategories(),types=new Set(cats.map(c=>c.type));el.selectedCount.textContent=cats.length;el.selectedTypes.textContent=types.size;el.generate.disabled=!state.authenticated||!cats.length;el.summary.innerHTML=cats.length?`<span class="selection-pill"><strong>${cats.length}</strong> selecionada(s)</span>`+Object.keys(TYPE).map(t=>{const n=cats.filter(c=>c.type===t).length;return n?`<span class="selection-pill">${TYPE[t].label}: <strong>${n}</strong></span>`:''}).join(''):'<span class="selection-pill">Nenhuma categoria selecionada</span>';updateTabCounts()}
async function loadCategories(){if(state.loading)return;state.loading=true;state.authenticated=false;state.categories=[];state.selected.clear();el.workspace.classList.add('is-hidden');el.generate.disabled=true;setLoginOpen(false);setStatus('Analisando conta e categorias…','busy');el.load.disabled=true;try{const p=parseLogin(el.login.value);el.server.value=p.server;el.username.value=p.username;el.password.value=p.password;el.liveExt.value=p.liveExtension;const account=await request('');const active=account?.user_info&&(String(account.user_info.auth)==='1'||String(account.user_info.status||'').toLowerCase()==='active');if(!active)throw new Error('A conta não retornou status ativo.');const sources=chosenMode()==='shorts'?[['vod',TYPE.vod]]:Object.entries(TYPE);const groups=await Promise.all(sources.map(async([type,m])=>{try{return normalizeCategories(await request(m.action),type)}catch{return []}}));state.categories=groups.flat();state.authenticated=true;chooseInitialType();renderTypeTabs();renderCategories();updateSelection();el.workspace.classList.remove('is-hidden');const status=String(account?.user_info?.status||'Ativa');el.accountSummary.textContent=normalizeServer(el.server.value)+' · '+status;el.loginSummary.textContent='Conta válida · '+normalizeServer(el.server.value);const lc=state.categories.filter(c=>c.type==='live').length,vc=state.categories.filter(c=>c.type==='vod').length,sc=state.categories.filter(c=>c.type==='series').length;setStatus(chosenMode()==='shorts'?('Conta válida. '+vc+' categorias de filmes encontradas.'):('Conta válida · TV '+lc+' · Filmes '+vc+' · Séries '+sc+'.'),'ok')}catch(e){resetWorkspace(e.message);setStatus(e.message,'err');el.loginSummary.textContent='Falha na análise · revise o M3U/proxy';setLoginOpen(true);setTimeout(()=>el.login.focus(),80)}finally{state.loading=false;el.load.disabled=false}}
async function loadRemoteTemplate(mode){const url=SRH_MODULE_BASE+'/templates/'+(mode==='shorts'?'shorts':'standard')+'.html?v='+encodeURIComponent(TEMPLATE_REV);const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('Falha ao baixar template remoto: HTTP '+r.status);return await r.text()}
function upgradeTemplate(template,mode){let t=String(template||'');if(mode==='shorts'){t=t.replace(/shorts-splash-r4/g,'shorts-aura-r5');if(!t.includes('05-aura-transport-r5.js')){t=t.replace("JS_PATCH=BASE+'/runtime/shorts/04-proxy-fix.js'","JS_PATCHES=[BASE+'/runtime/shorts/04-proxy-fix.js',BASE+'/runtime/shorts/05-aura-transport-r5.js']");t=t.replace('...JS_CORE,JS_PATCH]','...JS_CORE,...JS_PATCHES]');t=t.replace('patch=await get(JS_PATCH);',"patch=(await Promise.all(JS_PATCHES.map(get))).join('\\n');")}}else{t=t.replace(/aura625-r10/g,'aura625-r11');if(!t.includes('11-aura-transport-r11.js'))t=t.replace("BASE+'/runtime/standard/10-actions-accessibility.js'];","BASE+'/runtime/standard/10-actions-accessibility.js',BASE+'/runtime/standard/11-aura-transport-r11.js'];")}return t}
function safeFilename(v){return String(v||'app').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_-]+/gi,'_').replace(/^_+|_+$/g,'')||'app'}
async function generate(){const mode=chosenMode(),targets=selectedCategories().filter(c=>mode!=='shorts'||c.type==='vod').map(c=>({type:c.type,name:c.name}));if(!targets.length)return;const config={appId:'srh_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7),appMode:mode,appName:el.appName.value.trim()||'Meu App',server:normalizeServer(el.server.value),username:el.username.value.trim(),password:el.password.value.trim(),liveExtension:el.liveExt.value,corsProxy:el.corsProxy.value.trim(),theme:chosenTheme(),targets};el.generate.disabled=true;setStatus('Carregando módulos compactos…','');try{let template=await loadRemoteTemplate(mode);template=upgradeTemplate(template,mode);const json=JSON.stringify(config).replace(/</g,'\\u003c'),html=template.replace('__APP_CONFIG__',json),blob=new Blob([html],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=safeFilename(config.appName)+(mode==='shorts'?'_Shorts':'')+'.html';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200);setStatus((mode==='shorts'?'App Shorts mesclado':'App padrão')+' R11 gerado com '+targets.length+' categoria(s).','ok')}catch(e){setStatus(e.message||'Falha ao carregar template remoto.','error')}finally{el.generate.disabled=false}}
function onModeChange(){state.activeType=chosenMode()==='shorts'?'vod':'live';if(state.authenticated){resetWorkspace('Formato alterado. Analise novamente para consultar apenas o necessário.');el.loginSummary.textContent='Formato alterado · analisar novamente';setLoginOpen(true)}}
el.loginToggle.onclick=()=>{if(!state.loading)setLoginOpen(!el.loginPanel.classList.contains('is-open'))};el.editLogin.onclick=()=>setLoginOpen(true);el.load.onclick=loadCategories;el.search.oninput=renderCategories;el.all.onclick=()=>{state.categories.filter(c=>c.type===state.activeType).forEach(c=>state.selected.add(c.type+'::'+c.id));renderCategories();updateSelection()};el.clear.onclick=()=>{[...state.selected].forEach(k=>{if(k.startsWith(state.activeType+'::'))state.selected.delete(k)});renderCategories();updateSelection()};el.generate.onclick=generate;el.styleToggle.onclick=()=>el.stylePanel.classList.toggle('is-open');$$('input[name="theme"]').forEach(r=>r.onchange=()=>{el.styleCurrent.textContent=r.dataset.label||r.value;setTimeout(()=>el.stylePanel.classList.remove('is-open'),100)});$$('input[name="appMode"]').forEach(r=>r.onchange=onModeChange);$$('[data-type]').forEach(btn=>btn.onclick=()=>{if(btn.disabled)return;state.activeType=btn.dataset.type;el.search.value='';renderTypeTabs();renderCategories()});
})();
